name: cleanarcjh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Http Request
  dio: ^5.8.0+1

  #
  equatable: ^2.0.7

  # State Management
  flutter_bloc: ^9.1.0

  # Responsive UI packackage
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  logger: ^2.5.0
  internet_connection_checker: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  easy_localization: ^3.0.7+1
  flutter_toastr: ^1.0.3

  pluto_grid: ^8.0.0
  badges: ^3.1.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to

  flutter_lints: ^5.0.0
  
  build_runner: null
  flutter_gen_runner: null


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/fonts/


