// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4N2_CS6ywezI01z3jIOrKN2LFckRZk8',
    appId: '1:1058733748641:web:d938f7965fdba1cd3edbe0',
    messagingSenderId: '1058733748641',
    projectId: 'salamasd',
    authDomain: 'salamasd.firebaseapp.com',
    storageBucket: 'salamasd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbrEggWaL-cuuBPyqabqKkOUO0sjdML4',
    appId: '1:1058733748641:android:0cec1a43d7b058663edbe0',
    messagingSenderId: '1058733748641',
    projectId: 'salamasd',
    storageBucket: 'salamasd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMzX0uMPi3Q2OD8XcNc6pKeduuTuHZX0',
    appId: '1:1058733748641:ios:67d8766bd8ea08fe3edbe0',
    messagingSenderId: '1058733748641',
    projectId: 'salamasd',
    storageBucket: 'salamasd.firebasestorage.app',
    iosBundleId: 'com.example.cleanarcjh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgMzX0uMPi3Q2OD8XcNc6pKeduuTuHZX0',
    appId: '1:1058733748641:ios:67d8766bd8ea08fe3edbe0',
    messagingSenderId: '1058733748641',
    projectId: 'salamasd',
    storageBucket: 'salamasd.firebasestorage.app',
    iosBundleId: 'com.example.cleanarcjh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ4N2_CS6ywezI01z3jIOrKN2LFckRZk8',
    appId: '1:1058733748641:web:1c9638dc269fd1413edbe0',
    messagingSenderId: '1058733748641',
    projectId: 'salamasd',
    authDomain: 'salamasd.firebaseapp.com',
    storageBucket: 'salamasd.firebasestorage.app',
  );

}